version: '2'
#version: '3'

services:

  app:
    build:
      context: .
    environment:
      TWITTER_TRACK_KEYWORD: "juliaaano"
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_ACCESS_TOKEN:
      TWITTER_ACCESS_TOKEN_SECRET:
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_USERNAME: "root"
      INFLUXDB_PASSWORD: "root"
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
    links:
      - influxdb

  influxdb:
    image: influxdb:1.2.2
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb

volumes:

  logs:
    driver: local

  influxdb:
    driver: local

networks:

  default:
    driver: bridge
