FROM maven:3

MAINTAINER Juliano Boesel Mohr <juliaaano@gmail.com>

COPY ./ ./build

RUN mvn -q -f build clean package -DskipTests \
	&& mkdir app \
	&& mv build/target/twitter-feed-*.jar app/app.jar \
	&& rm -rf build

WORKDIR /app

VOLUME /app/logs

EXPOSE 8000

CMD ["java", "-jar", "app.jar"]
