version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-build
    environment:
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_ACCESS_TOKEN:
      TWITTER_ACCESS_TOKEN_SECRET:
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - maven:/root/.m2

volumes:

  logs:
    driver: local

  maven:
    driver: local

networks:

  default:
    driver: bridge
