apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-feed-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: twitter-feed
    spec:
      containers:
      - name: twitter-feed
        image: juliaaano/twitter-feed:1.0.0
        env:
        - name: TWITTER_TRACK_KEYWORD
          value: "TyroCodeBlitz,Tyro,CodeBlitz"
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: TWITTER_CONSUMER_KEY
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: TWITTER_CONSUMER_SECRET
        - name: TWITTER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: TWITTER_ACCESS_TOKEN
        - name: TWITTER_ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: TWITTER_ACCESS_TOKEN_SECRET
        - name: INFLUXDB_URL
          value: "http://influxdb-svc:8086"
        - name: INFLUXDB_USERNAME
          value: "root"
        - name: INFLUXDB_PASSWORD
          value: "root"
#        imagePullPolicy: Always
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-logs
        emptyDir: {}
