apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
  - name: http
    port: 8083
    nodePort: 30001
  - name: api
    port: 8086
    nodePort: 30002
